zone                = "asia-southeast1-a"
arch                = "x86-64"
source_image_family = "ubuntu-2204-lts"
image_family        = "development-server"
project_id          = "project-devops-share-rs"