version: "3"

networks:
  metrics-server:

volumes:
  aletmanager-data:
  prometheus-data:
  loki-data:
  
services:
  alert-manager:
    image: prom/alertmanager
    container_name: alert-manager
    restart: always
    volumes:
      - "./config/alertmanager/alertmanager.yml:/alertmanager/alertmanager.yml"
      - "aletmanager-data:/alertmanager/data"
    networks:
      - metrics-server
    ports:
      - 9093:9093

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
    volumes:
      - "./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml"
      - "./config/prometheus/alert.rules.yaml:/etc/prometheus/alert.rules.yml"
      - "prometheus-data:/prometheus"
    networks:
      - metrics-server
    ports:
      - 9090:9090

  node-exporter:
    image: prom/node-exporter
    restart: always
    networks:
      - metrics-server
    ports:
      - 9100:9100

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki/config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - metrics-server